### ISSUE TITLE
better layout universal keyboard

### ISSUE THREAD

**Issue by 0xtrzy** [system76/launch#13]
Please look at https://klawiatura.wordpress.com/wersja-mini/
this layout 
![kl](https://user-images.githubusercontent.com/59196690/107624469-36137280-6c5b-11eb-91c9-41ca40b9b8e8.jpg)
better nationality char, '+' without shift, more functions key and two potenciometer knob , volume control or manipulate 3d object. 

if fit small clock and info about internet connection this will be complete design

**Comment by leviport** [comment]
Thank you for the recommendation! Deviating from a staggered layout was something we wanted to avoid since it would ruin muscle memory for most users. While I personally prefer ortholinear layouts myself, I fully appreciate that most users do not share my preference. 

As far as the characters that are bound to each key -- they will ship with a standard QWERTY layout since this is what most users will want to start with. We're aiming to make remapping easy enough to satisfy everyone who wants something different.
