### ISSUE TITLE
Where's the link to buy this one ?

### ISSUE THREAD

**Issue by alexserver** [system76/launch#15]
In the readme there's no link to a store or form to buy this one.
Also, it doesn't say whether this keyboard is just in the design phase, or already in production.
Can you put the enough information in your readme to clarify this questions ?
- is it on sale already ?
- is this only a design ?
- where are the schemas to build one ?
- do I have to build the PCB using PCB printing services ?
- do you have plans to sell this one ?

**Comment by leviport** [comment]
The readme is not a blog post or official announcement, so that information wouldn't be relevant here. This is just where all the source code lives. They are not ready for sale quite yet, but we will make announcements in all of the usual places when they are selling. All of the design files are in this repo, so you can try making one yourself if you want to.
