### ISSUE TITLE
Consider configuring as Dvorak layout as an option.

### ISSUE THREAD

**Issue by TeamLinux01** [system76/launch#35]
It seems like a user could pop off all the keys and reconfigure the keyboard to Dvorak layout, but it might be easier for the customer (if there is a demand) to have it shipped in that layout.

I just wanted to throw the idea out there.

https://www.dvorak-keyboard.com/

**Comment by leviport** [comment]
Thanks for the suggestion! Shipping with custom layouts would make the fulfillment process far more complicated than we would want it to be, but that's why we made it easy to import and export Launch layouts with the [configurator](https://github.com/pop-os/keyboard-configurator/). Once you have a Dvorak layout (such as [mine](https://gist.github.com/leviport/d7bce60015fd5b1b03506679205cd0d9)), you'll be able to import it and make any tweaks and customizations you want to it, then share it with your friends so they can make their own tweaks and modifications.

Since Launch uses a uniform XDA profile, moving the physical keycaps into Dvorak will not mess up the key profile like it would on keyboards that use a sculpted keycap profile. Launch is shipped with a keycap puller in order to help make any post-shipment customizations.

For reference, here is what my map looks like:
![levi-layout](https://user-images.githubusercontent.com/13512097/120842930-ab68c300-c52a-11eb-87dc-414004516351.png)
