### ISSUE TITLE
Feature Request: Allow multiple binds (at least to modifier keys).

### ISSUE THREAD

**Issue by Vashinator** [system76/launch#83]
My use case is something like OBS. I need a host of shortcut keys that won't interfere with me typing in the terminal or in an app, etc.

One way I was thinking of accomplishing this is by using the numpad and doing something like adding super + ctrl + alt + shift keys plus the respective numpad keys.

Ex. Numpad 1 would actually be: super + ctrl + alt + shift + numbpad 1. I could then freely bind this in OBS without any worries of this conflicting with something else.

Edit: I see you have screen up and down for Gnome based systems, but as I primarily use KDE Plasma or a WM, these options don't really help me. I could see a move left or move right option being nice in KDE Plasma. This type of setup could be accomplished with this as well.

This is akin to what ZSA does: https://ergodox-ez.com/our-open-source-firmware
After selecting 1, I can then do the following:
![image](https://user-images.githubusercontent.com/115740398/232234003-684faf88-03e9-408b-bf9d-0f1ef1ec481f.png)

**Comment by leviport** [comment]
Similarly with #83, Launch already does support this functionality, it's just the configurator that doesn't yet support it. This kind of advanced functionality is definitely planned and being [worked on](https://github.com/pop-os/keyboard-configurator/issues/146) though, so it's only a matter of time before [manually flashing QMK firmware](https://github.com/system76/qmk_firmware/blob/master/keyboards/system76/launch_1/readme.md) isn't necessary to achieve this functionality. 

Since we're tracking these new features in https://github.com/pop-os/keyboard-configurator/issues/146, I'm going to close this issue.
